editorconfig/specification

index.rst

This should save a lot of clarifications.

Add a link to the current Plugin Guidelines

---

README.md
index.rst

I had a great time hanging out with @florianb in Berlin yesternight and we hashed out which parts of the EditorConfig specification needed clarification. This PR is the result of these conversations, combined with a couple of open issues.
Fixes #8
Fixes #2

Clarify specification

---

index.rst

The motivation behind this change is to simplify the spec by not introducing a new word, declaration, but instead just use "pairs", which is obviously related to key-value pairs and not ambiguous at all.

Declarations -> Pairs

---

Makefile
conf.py

I ran across two minor hiccups when building the specification on my local machine for the first time.  This PR fixes both.
1.  There is no `make clean`.  This PR adds a `clean` target to the Makefile for convenience.  I did not try to add one to `make.bat` since I am much rustier on batch-file syntax than on Makefile syntax.
2. When I ran `make html`, I got a warning:
> copying static files... WARNING: html_static_path entry '/home/cxw/proj/editorconfig-specification/_static' does not exist
This PR removes the static path from conf.py.  This removes that warning.  Since there are no static files currently, there is no change in functionality.
Thanks for considering this PR!

Makefile: add `clean`, fix warning

---

index.rst

? does not match path separators. Closes editorconfig/editorconfig#424

Update description for ? pattern

---

index.rst

I propose these changes to implement editorconfig/editorconfig-vote#11.  I look forward to any comments and questions!
- The versioning information is a new section at the end.
- I added a "definitions" section at the beginning to make the versioning section clearer.
- I did some minor cleanup (spelling, table header)
NOTE: Not all the changes approved by vote 11 are in the specification.  Items still open, to be done after this PR is merged, are:
> - bump editorconfig-core-test to v0.13 to mark this change
> - update the core tests (or accept a PR) [here](https://github.com/editorconfig/editorconfig-core-test/blob/b8f30cfea1d1c1cd46219280ad4eb27780d21f7b/cli/CMakeLists.txt#L29) to permit major.minor version numbers (no patch)
Thanks for considering this PR, and for voting in favor of my …

Implement versioning changes

---

README.md
conf.py
index.rst

Implements https://github.com/editorconfig/editorconfig-vote/issues/12.
Ref.: editorconfig/editorconfig#395
In #17, I didn't realize v0.13 of editorconfig-core-test had already been tagged.  Therefore, I propose bumping the version at line 217 to v0.14.0 and tagging editorconfig-core-test in its current state as 0.14.0.

Spec version follows Semantic Versioning 2.0.0

---

index.rst

- Remove the upper limit for section name, key and value length.
- Permit implementations to define their own upper limits.
- Add minimum supported lengths each implementation must support.

editorconfig/editorconfig#429 Remove section name, key and value length limits

---

README.md

Fix broken link to built version on readthedocs.io

---

index.rst

Related https://github.com/editorconfig/editorconfig-core-test/issues/46

Clarify the wording of inserting `#` or `;` to the end of a line

---

conf.py
index.rst

It looks like the current wording still leads to too much confusion: https://github.com/editorconfig/specification/pull/29#discussion_r783382976
I therefore propose to remove the explaining addition about inline comments at all, in favor of a description of the former behavior of EditorConfig parsers.

Remove the description of inline comments at all

---

index.rst

Our text blocks are not in a recognized language.  Since the colors are wrong, turn them off!
Before: 
After:

Turn off syntax highlighting of text blocks

---

conf.py
index.rst

Context: https://github.com/editorconfig/editorconfig-core-test/issues/50 asked why a core had to report keys like `key=value`.  I looked at the spec, and realized that wasn't expressly called out.
Change:
- Terminology: reference key-value pairs
- Supported Pairs: state that cores must report all key-value pairs.
- Bump version to 0.15.1

Clarify that cores report all keys, whether or not supported

---

index.rst

This is a negligence when writing the spec. The tests have already been enforcing it since long time ago:
- https://github.com/editorconfig/editorconfig-core-test/blob/5ca0b296dc31124d0303895c163013450bd97958/glob/CMakeLists.txt#L129-L130
- https://github.com/editorconfig/editorconfig-core-test/blob/5ca0b296dc31124d0303895c163013450bd97958/glob/braces.in#L10-L11
Fix editorconfig/editorconfig-emacs#315

Clarify that curly braces only match literally without commas

---

.editorconfig
.readthedocs.yaml
conf.py
index.rst

Resolves https://github.com/editorconfig/editorconfig/issues/315 .
To specify the natural language for which spelling should be checked.
**Open questions:**
- Should we use [RFC 5646](https://www.rfc-editor.org/rfc/rfc5646) tags instead of `xx_YY` ([ISO/IEC 15897](https://en.wikipedia.org/wiki/ISO/IEC_15897)) tags?  The RFC is freely available, which the ISO standard is not.
- If we do use ISO tags, should we restrict values at all?  E.g., only alpha-2?  Or expressly specify that alpha-3 is also accepted?

Add spelling_language property

---

conf.py

readthedoc will deprecate setting html_baseurl automatically soon soon. Now we set it explicitly in conf.py.
https://about.readthedocs.com/blog/2024/07/addons-by-default/#how-does-it-affect-my-projects

Set html_baseurl

---

index.rst

This is consistent with the rules from `.gitignore`: <https://git-scm.com/docs/gitignore>
> If there is a separator at the beginning or middle (or both) of the
> pattern, then the pattern is relative to the directory level of the
> particular .gitignore file itself. Otherwise the pattern may also match
> at any level below the .gitignore level.
Since we intend to be consistent with `.gitignore`, this part of the spec has been unclear.
Fix editorconfig/editorconfig#509
----
📚 Documentation preview 📚: https://editorconfig-specification--49.org.readthedocs.build/

Clarify the effects of path separator

---

.github/workflows/preview.yml

Seems like pull_request_target grants more permission, and thus allow preview from a fork: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
Related: https://github.com/readthedocs/actions/issues/23
Fix #52

Use pull_request_target instead of pull_request

---

.github/workflows/preview.yml

Not sure if it can fix #52
----
📚 Documentation preview 📚: https://editorconfig-specification--57.org.readthedocs.build/

Rename readthedocs action name

---

conf.py
index.rst

We do not support the ISO numeric or three-letter codes.
Fixes #48
Reported by @gustaphe at <https://github.com/editorconfig/editorconfig-vim/pull/210#issuecomment-2043070775>.
----
📚 Documentation preview 📚: https://editorconfig-specification--54.org.readthedocs.build/

spelling_language clarification: ss, TT are two-character codes

---

index.rst

Fix editorconfig/editorconfig#493
----
📚 Documentation preview 📚: https://editorconfig-specification--58.org.readthedocs.build/

Clarify that a section name ending with / does not match any file

---

conf.py
index.rst

* Section names can have trailing whitespace (the core tests expressly check this).
* When deciding what kind of line we have, all leading whitespace is ignored, and the trailing LF or CRLF is also ignored.
* Blank lines do not have to include whitespace.
* Fix some typos (change Markdown single-backticks to rst double-backticks).
Fixes https://github.com/editorconfig/editorconfig/issues/500

Clarify whitespace handling 

---

index.rst

Fixes #30
----
📚 Documentation preview 📚: https://editorconfig-specification--60.org.readthedocs.build/

Supported properties: Clarify semantics of "root"

---

index.rst

Clarify, in the spec, that editors must not insert newlines into empty files (otherwise you could never edit a zero-byte file!).
Fixes #15.
----
📚 Documentation preview 📚: https://editorconfig-specification--61.org.readthedocs.build/

insert_final_newline: don't do so on an empty file

---

index.rst

**Note:** This PR builds on #46.  Please review **only** the head commit.  All other commits are part of #46.
Part of https://github.com/editorconfig/editorconfig/issues/496 .
Update the spec to expressly permit the form
```
key =
```
as defining `key` with an empty string as its value.  This is different from not defining `key` at all.
@ppalaga has written draft tests at https://github.com/editorconfig/editorconfig-core-test/pull/52 .

Allow empty values in the spec

---

index.rst

There is an example in Glob Expressions where no file separator is involved for `*.c` in the spec. However, this example is a bit confusing, since it does not explicitly state that `*.c` does not only mean files in the current directory, where `.edictorconfig` is stored, but rather it applies to all files recursively below as well as the files in current directory.
So this PR just makes this explicit in the example. 
----
📚 Documentation preview 📚: https://editorconfig-specification--63.org.readthedocs.build/

Clarified Glob Expressions example with no path separator

---

index.rst

Clarified the behavior of glob expressions
----
📚 Documentation preview 📚: https://editorconfig-specification--67.org.readthedocs.build/

Clarifed Glob expressions spec

---

index.rst

This has been generally assumed since we don't specifically mention other capitalizations, and core libraries have also assumed so. However, some communities seem to have used capital letters in some places, and it's best if we can clarify.
If we go the other route, as a standard, the current core libraries would break because they don't work consistently with each other. Additionally, core libraries are cumbersome to implement on case-sensitive filesystems, because they always have to use some regex to search the `.editorconfig` file in a directory, instead of just pointing to the file named `.editorconfig`.
Close editorconfig/editorconfig#523
----
📚 Documentation preview 📚: https://editorconfig-specification--70.org.readthedocs.build/

Clarify the case sensitivity of .editorconfig file

---

index.rst

Solves #74 
----
📚 Documentation preview 📚: https://editorconfig-specification--75.org.readthedocs.build/

Clarified conflicting rules in multiple sections defined in the same .editorconfig file when matched for single file

---

index.rst

Fix editorconfig/editorconfig#539
----
📚 Documentation preview 📚: https://editorconfig-specification--77.org.readthedocs.build/

Fix code format

---

index.rst

Resolves #19 
----
📚 Documentation preview 📚: https://editorconfig-specification--68.org.readthedocs.build/

GH-19 clarified leading slash in the spec

---

index.rst

Close #78 
----
📚 Documentation preview 📚: https://editorconfig-specification--79.org.readthedocs.build/

Replace the term rules with more accurate wording

---

index.rst

----
📚 Documentation preview 📚: https://editorconfig-specification--82.org.readthedocs.build/

spelling: case-insensitive

---

index.rst

Closes #86 
CC: @xuhdev 
----
📚 Documentation preview 📚: https://editorconfig-specification--87.org.readthedocs.build/

Added a small section addressing empty editorconfig files
